controller_manager:
  ros__parameters:
    update_rate: 30
    controllers:
      - diff_drive_controller
      - joint_broad
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_front_joint", "left_wheel_back_joint"]
    right_wheel_names: ["right_wheel_front_joint", "right_wheel_back_joint"]
    wheel_separation: 1.17
    wheel_radius: 0.26
    publish_rate: 50.0

