ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    output_frame: odom
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    use_sim_time: true

    imu0: "/imu/data"
    imu0_config: [false, false, false,  # x, y, z (position)
                  true, true, true,     # roll, pitch, yaw
                  false, false, false,  # x, y, z (velocity)
                  true, true, true,     # roll, pitch, yaw velocity
                  false, false, false]  # x, y, z (acceleration)
    imu0_differential: false
    imu0_relative: true

    gps0: "/gps/fix"
    gps0_config: [true, true, false,   # x, y, z (position)
                  false, false, false, # orientation
                  false, false, false, # velocity
                  false, false, false] # acceleration