/oak:
  ros__parameters:
    camera.i_calibration_dump: false
    camera.i_enable_diagnostics: true
    camera.i_enable_imu: true
    camera.i_enable_ir: true
    camera.i_enable_sync: true
    camera.i_external_calibration_path: ''
    camera.i_floodlight_brightness: 0
    camera.i_ip: ''
    camera.i_laser_dot_brightness: 800
    camera.i_mx_id: ''
    camera.i_nn_type: none
    camera.i_pipeline_dump: false
    camera.i_pipeline_type: RGBD
    camera.i_publish_tf_from_calibration: false
    camera.i_restart_on_diagnostics_error: false
    camera.i_rs_compat: false
    camera.i_tf_base_frame: oak
    camera.i_tf_cam_pitch: '0.0'
    camera.i_tf_cam_pos_x: '0.0'
    camera.i_tf_cam_pos_y: '0.0'
    camera.i_tf_cam_pos_z: '0.0'
    camera.i_tf_cam_roll: '0.0'
    camera.i_tf_cam_yaw: '0.0'
    camera.i_tf_camera_model: ''
    camera.i_tf_camera_name: oak
    camera.i_tf_custom_urdf_location: ''
    camera.i_tf_custom_xacro_args: ''
    camera.i_tf_imu_from_descr: 'false'
    camera.i_tf_parent_frame: oak-d-base-frame
    camera.i_usb_port_id: ''
    camera.i_usb_speed: SUPER_PLUS
    diagnostic_updater.period: 1.0
    diagnostic_updater.use_fqn: false
    imu.i_acc_cov: 0.0
    imu.i_acc_freq: 400
    imu.i_acc_mode: ACCELEROMETER_RAW
    imu.i_enable_acc: true
    imu.i_enable_gyro: true
    imu.i_enable_mag: true
    imu.i_enable_rotation: false
    imu.i_get_base_device_timestamp: false
    imu.i_gyro_cov: 0.0
    imu.i_gyro_freq: 400
    imu.i_gyro_mode: GYROSCOPE_RAW
    imu.i_max_q_size: 8
    imu.i_message_type: IMU
    imu.i_sync_method: LINEAR_INTERPOLATE_ACCEL
    imu.i_update_ros_base_time_on_ros_msg: false
    imu.i_rot_cov: -1.0
    imu.i_mag_cov: 0.0
    left.i_add_exposure_offset: false
    left.i_board_socket_id: 1
    left.i_calibration_file: ''
    left.i_disable_node: false
    left.i_enable_feature_tracker: false
    left.i_enable_lazy_publisher: true
    left.i_enable_nn: false
    left.i_exposure_offset: 0
    left.i_fps: 30.0
    left.i_fsync_continuous: false
    left.i_fsync_trigger: false
    left.i_get_base_device_timestamp: false
    left.i_height: 480
    left.i_low_bandwidth: false
    left.i_low_bandwidth_bitrate: 0
    left.i_low_bandwidth_ffmpeg_encoder: libx264
    left.i_low_bandwidth_frame_freq: 30
    left.i_low_bandwidth_profile: 4
    left.i_low_bandwidth_quality: 50
    left.i_max_q_size: 30
    left.i_publish_compressed: false
    left.i_publish_topic: false
    left.i_resolution: 400P # default 480P
    left.i_reverse_stereo_socket_order: false
    left.i_sensor_img_orientation: AUTO
    left.i_set_isp3a_fps: false
    left.i_simulate_from_topic: false
    left.i_simulated_topic_name: ''
    left.i_synced: false
    left.i_update_ros_base_time_on_ros_msg: false
    left.i_width: 640
    left.r_auto_exp_region_height: 0
    left.r_auto_exp_region_start_x: 0
    left.r_auto_exp_region_start_y: 0
    left.r_auto_exp_region_width: 0
    left.r_auto_exposure_limit: 1000
    left.r_chroma_denoise: 1
    left.r_exposure: 1000
    left.r_iso: 800
    left.r_luma_denoise: 1
    left.r_set_auto_exp_region: false
    left.r_set_auto_exposure_limit: false
    left.r_set_chroma_denoise: false
    left.r_set_luma_denoise: false
    left.r_set_man_exposure: false
    left.r_set_sharpness: false
    left.r_sharpness: 1
    oak.rgb.image_raw.enable_pub_plugins:
    - image_transport/compressedDepth
    - image_transport/compressed
    - image_transport/raw
    - image_transport/theora
    oak.rgb.image_raw.format: jpeg
    oak.rgb.image_raw.jpeg_quality: 95
    oak.rgb.image_raw.png_level: 3
    oak.rgb.image_raw.tiff.res_unit: inch
    oak.rgb.image_raw.tiff.xdpi: -1
    oak.rgb.image_raw.tiff.ydpi: -1
    oak.stereo.image_raw.enable_pub_plugins:
    - image_transport/compressedDepth
    - image_transport/compressed
    - image_transport/raw
    - image_transport/theora
    oak.stereo.image_raw.format: jpeg
    oak.stereo.image_raw.jpeg_quality: 95
    oak.stereo.image_raw.png_level: 3
    oak.stereo.image_raw.tiff.res_unit: inch
    oak.stereo.image_raw.tiff.xdpi: -1
    oak.stereo.image_raw.tiff.ydpi: -1
    pipeline_gen.i_enable_diagnostics: true
    pipeline_gen.i_enable_imu: true
    pipeline_gen.i_enable_sync: false
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    rgb.i_add_exposure_offset: false
    rgb.i_board_socket_id: 0
    rgb.i_calibration_file: ''
    rgb.i_color_order: BGR
    rgb.i_disable_node: false
    rgb.i_enable_feature_tracker: false
    rgb.i_enable_lazy_publisher: true
    rgb.i_enable_nn: false
    rgb.i_enable_preview: false
    rgb.i_exposure_offset: 0
    rgb.i_fps: 30.0
    rgb.i_fsync_continuous: false
    rgb.i_fsync_trigger: false
    rgb.i_get_base_device_timestamp: false
    rgb.i_height: 720
    rgb.i_interleaved: false
    rgb.i_isp_den: 3
    rgb.i_isp_num: 2
    rgb.i_keep_preview_aspect_ratio: true
    rgb.i_low_bandwidth: false
    rgb.i_low_bandwidth_bitrate: 0
    rgb.i_low_bandwidth_ffmpeg_encoder: libx264
    rgb.i_low_bandwidth_frame_freq: 30
    rgb.i_low_bandwidth_profile: 4
    rgb.i_low_bandwidth_quality: 50
    rgb.i_max_q_size: 30
    rgb.i_output_isp: true
    rgb.i_preview_height: 300
    rgb.i_preview_size: 300
    rgb.i_preview_width: 300
    rgb.i_publish_compressed: false
    rgb.i_publish_topic: true
    rgb.i_resolution: 1080P
    rgb.i_reverse_stereo_socket_order: false
    rgb.i_sensor_img_orientation: AUTO
    rgb.i_set_isp3a_fps: false
    rgb.i_set_isp_scale: true
    rgb.i_simulate_from_topic: false
    rgb.i_simulated_topic_name: ''
    rgb.i_synced: false
    rgb.i_update_ros_base_time_on_ros_msg: false
    rgb.i_width: 1280
    rgb.r_auto_exp_region_height: 0
    rgb.r_auto_exp_region_start_x: 0
    rgb.r_auto_exp_region_start_y: 0
    rgb.r_auto_exp_region_width: 0
    rgb.r_auto_exposure_limit: 1000
    rgb.r_chroma_denoise: 1
    rgb.r_exposure: 20000
    rgb.r_focus: 1
    rgb.r_iso: 800
    rgb.r_luma_denoise: 1
    rgb.r_set_auto_exp_region: false
    rgb.r_set_auto_exposure_limit: false
    rgb.r_set_chroma_denoise: false
    rgb.r_set_luma_denoise: false
    rgb.r_set_man_exposure: false
    rgb.r_set_man_focus: false
    rgb.r_set_man_whitebalance: false
    rgb.r_set_sharpness: false
    rgb.r_sharpness: 1
    rgb.r_whitebalance: 3300
    right.i_add_exposure_offset: false
    right.i_board_socket_id: 2
    right.i_calibration_file: ''
    right.i_disable_node: false
    right.i_enable_feature_tracker: false
    right.i_enable_lazy_publisher: true
    right.i_enable_nn: false
    right.i_exposure_offset: 0
    right.i_fps: 30.0
    right.i_fsync_continuous: false
    right.i_fsync_trigger: false
    right.i_get_base_device_timestamp: false
    right.i_height: 480
    right.i_low_bandwidth: false
    right.i_low_bandwidth_bitrate: 0
    right.i_low_bandwidth_ffmpeg_encoder: libx264
    right.i_low_bandwidth_frame_freq: 30
    right.i_low_bandwidth_profile: 4
    right.i_low_bandwidth_quality: 50
    right.i_max_q_size: 30
    right.i_publish_compressed: false
    right.i_publish_topic: false
    right.i_resolution: 400P # default 480P
    right.i_reverse_stereo_socket_order: false
    right.i_sensor_img_orientation: AUTO
    right.i_set_isp3a_fps: false
    right.i_simulate_from_topic: false
    right.i_simulated_topic_name: ''
    right.i_synced: false
    right.i_update_ros_base_time_on_ros_msg: false
    right.i_width: 640
    right.r_auto_exp_region_height: 0
    right.r_auto_exp_region_start_x: 0
    right.r_auto_exp_region_start_y: 0
    right.r_auto_exp_region_width: 0
    right.r_auto_exposure_limit: 1000
    right.r_chroma_denoise: 1
    right.r_exposure: 1000
    right.r_iso: 800
    right.r_luma_denoise: 1
    right.r_set_auto_exp_region: false
    right.r_set_auto_exposure_limit: false
    right.r_set_chroma_denoise: false
    right.r_set_luma_denoise: false
    right.r_set_man_exposure: false
    right.r_set_sharpness: false
    right.r_sharpness: 1
    stereo.i_add_exposure_offset: false
    stereo.i_align_depth: true
    stereo.i_bilateral_sigma: 0
    stereo.i_board_socket_id: 0
    stereo.i_calibration_file: ''
    stereo.i_depth_filter_size: 5
    stereo.i_depth_preset: HIGH_ACCURACY
    stereo.i_disparity_width: DISPARITY_96
    stereo.i_enable_alpha_scaling: false
    stereo.i_enable_brightness_filter: false
    stereo.i_enable_companding: false
    stereo.i_enable_decimation_filter: false
    stereo.i_enable_disparity_shift: false
    stereo.i_enable_distortion_correction: false
    stereo.i_enable_lazy_publisher: true
    stereo.i_enable_spatial_filter: false
    stereo.i_enable_spatial_nn: false
    stereo.i_enable_speckle_filter: false
    stereo.i_enable_temporal_filter: false
    stereo.i_enable_threshold_filter: false
    stereo.i_exposure_offset: 0
    stereo.i_extended_disp: false
    stereo.i_get_base_device_timestamp: false
    stereo.i_height: 720
    stereo.i_left_rect_add_exposure_offset: false
    stereo.i_left_rect_enable_feature_tracker: false
    stereo.i_left_rect_exposure_offset: 0
    stereo.i_left_rect_low_bandwidth: false
    stereo.i_left_rect_low_bandwidth_bitrate: 0
    stereo.i_left_rect_low_bandwidth_ffmpeg_encoder: libx264
    stereo.i_left_rect_low_bandwidth_frame_freq: 30
    stereo.i_left_rect_low_bandwidth_profile: 4
    stereo.i_left_rect_low_bandwidth_quality: 50
    stereo.i_left_rect_publish_compressed: false
    stereo.i_left_rect_publish_topic: false
    stereo.i_left_rect_synced: false
    stereo.i_left_socket_id: 1
    stereo.i_low_bandwidth: false
    stereo.i_low_bandwidth_bitrate: 0
    stereo.i_low_bandwidth_ffmpeg_encoder: libx264
    stereo.i_low_bandwidth_frame_freq: 30
    stereo.i_low_bandwidth_profile: 4
    stereo.i_low_bandwidth_quality: 50
    stereo.i_lr_check: true
    stereo.i_lrc_threshold: 10
    stereo.i_max_q_size: 30
    stereo.i_output_disparity: false
    stereo.i_publish_compressed: false
    stereo.i_publish_synced_rect_pair: false
    stereo.i_publish_topic: true
    stereo.i_rectify_edge_fill_color: 0
    stereo.i_reverse_stereo_socket_order: false
    stereo.i_right_rect_add_exposure_offset: false
    stereo.i_right_rect_enable_feature_tracker: false
    stereo.i_right_rect_exposure_offset: 0
    stereo.i_right_rect_low_bandwidth: false
    stereo.i_right_rect_low_bandwidth_bitrate: 0
    stereo.i_right_rect_low_bandwidth_ffmpeg_encoder: libx264
    stereo.i_right_rect_low_bandwidth_frame_freq: 30
    stereo.i_right_rect_low_bandwidth_profile: 4
    stereo.i_right_rect_low_bandwidth_quality: 50
    stereo.i_right_rect_publish_compressed: false
    stereo.i_right_rect_publish_topic: false
    stereo.i_right_rect_synced: false
    stereo.i_right_socket_id: 2
    stereo.i_set_disparity_to_depth_use_spec_translation: false
    stereo.i_set_input_size: false
    stereo.i_socket_name: rgb
    stereo.i_spatial_nn_source: right
    stereo.i_stereo_conf_threshold: 240
    stereo.i_subpixel: true
    stereo.i_subpixel_fractional_bits: 3
    stereo.i_synced: false
    stereo.i_update_ros_base_time_on_ros_msg: false
    stereo.i_width: 1280
    use_sim_time: false
